name 'docker-nexus'
maintainer 'Mark O''Connor'
maintainer_email 'mark@myspotontheweb.com'
license 'all_rights'
description 'Installs/Configures docker-nexus'
long_description 'Installs/Configures docker-nexus'
version '0.1.0'

depends 'apt'
depends 'docker'
